apiVersion: v1 
kind: Secret 
metadata: 
  name: mysql 
type: Opaque  
data: 
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop 
  labels:
    app: mysql
    project: roboshop 
    tier: db
spec:
  # modify replicas according to your case
  replicas: 1
  selector: # replica labels 
    matchLabels:
      app: mysql
      project: roboshop 
      tier: db
  template: # pod-definition
    metadata:
      labels:
        app: mysql
        project: roboshop 
        tier: db
    spec:
      containers:
      - name: mysql
        image: devopsprocloud/mysql:v1
        imagePullPolicy: Always 
        envFrom: 
        - secretRef: 
            name: mysql
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: mysql
  namespace: roboshop 
spec: 
  selector: 
   app: mysql  
   project: roboshop 
   tier: db  
  ports:
  - protocol: TCP 
    port: 3306 #service port 
    targetPort: 3306 #container port 